# Generated by Django 5.1.6 on 2025-02-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_mobile', models.CharField(max_length=15)),
                ('customer_email', models.CharField(max_length=15)),
                ('customer_password', models.CharField(max_length=15)),
            ],
        ),
    ]
