# Generated by Django 5.0.7 on 2025-03-03 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_organization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
