# Generated by Django 5.0.7 on 2025-03-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_customer_first_name_customer_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Organization',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
