# Generated by Django 5.0.7 on 2025-03-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_customer_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Organization',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_mobile',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='organization',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
