# Generated by Django 5.0.7 on 2025-03-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_customer_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='organization',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='Organization',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
